### ISSUE TITLE
[ENH] - Cleanup terminal prompt

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub#1157]
### Feature description

When opening a terminal in JupyterLab the prompt could do with some cleanup.

`dharhas@quansight.com@jupyter-dharhas-40quansight-2ecom:~$`

Does `jupyter-dharhas-40quansight-2ecom` have any significance. If not we should just use 

`dharhas@quansight.com:~$` as the prompt

Also, why is `/opt/conda/condabin/conda` be printed twice

We should also consider other things for a nice terminal prompt, i.e. git-prompt integration
 
![image](https://user-images.githubusercontent.com/561301/157780607-cb470b84-699e-41fb-905b-bf066d4a0d40.png)

### Value and/or benefit

A clean prompt greatly enhances the usability of the terminal.

**Comment by pierrotsmnrd** [comment]
This is a point I reported a few months ago when I collected the users' feedbacks.
What the users expect are : 
- the current directory
- the current conda environment
- the current git branch

Example inspired from my own zsh : 
``` 
psimonard@quansight.com:~/earthquakes/data
(current_env) > $                                                                        [my_git_branch]
```

**Comment by costrouc** [comment]
@dharhas this is resolved in https://github.com/Quansight/qhub/pull/1143 I'm going to link this PR to this issue. We've been waiting to merge that PR since we've had a feature freeze for 0.4.

**Comment by dharhas** [comment]
I like @pierrotsmnrd suggestion for what the prompt should show. Does #1143 fix that?

**Comment by viniciusdc** [comment]
> @dharhas currently #1143 fixes the issue with "/opt/conda/condabin..." being printed.
> 
> Do we have a PS1 prompt that should be used @pierrotsmnrd? It needs to be bash compatible. All I would need to do then is add the PS1 to the file and it should be available.

Hi @costrouc @dharhas, I was not able to generate a working example totally similar to what @pierrotsmnrd proposed, but I made this one 
![image](https://user-images.githubusercontent.com/51954708/159063803-93fd8db9-386e-406f-803c-4196c8e0da4f.png)
In theory, when installing conda the base environment should be added to it automatically (there is [this script](https://github.com/BCSharp/PSCondaEnvs/blob/master/activate.ps1) if needed as well)

The above PS1:
```bash
PS1='\[\e[0m\][\[\e[0m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\[\e[0m\]] \[\e[0m\]\u\[\e[0m\]:\[\e[0m\]\w\n \[\e[0m\]> \[\e[0m\]\$ \[\e[0m\]'
```

**Comment by pierrotsmnrd** [comment]
Hi everyone

I wasn't able to find a read-to-use PS1, my prompt is the `Bureau` Theme of zsh : https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/bureau.zsh-theme

I hope this helps.

**Comment by dharhas** [comment]
@costrouc @viniciusdc is this actually fixed. I'm still seeing the ugly prompt on qhub-beta
 
`dharhas@quansight.com@jupyter-dharhas-40quansight-2ecom:~/`

**Comment by viniciusdc** [comment]
> @costrouc @viniciusdc is this actually fixed? As far as I can tell, the issue was closed without the prompt actually being fixed OR there is no active deployment with the fix in place. qhub-beta still shows the old ugly bash prompt.
> 
> `dharhas@quansight.com@jupyter-dharhas-40quansight-2ecom:~/`

Hi, @dharhas the prompt configuration is currently set in [here](https://github.com/Quansight/qhub/blob/main/qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/skel/.bashrc), if I know what we would like to see I can make the necessary changes. 

The clean up of the terminal logs, should have been fixed with a certain PR, c.c @costrouc here

**Comment by dharhas** [comment]
@viniciusdc your proposal from 3 comments above is good enough for now. Please do a PR for that. We can tweak again later.

**Comment by dharhas** [comment]
@viniciusdc A clean way to get a nice prompt is to use

https://github.com/magicmonty/bash-git-prompt

We would need to vendor the script and the folder 

`git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1`

```
GIT_PROMPT_THEME=Solarized
source $HOME/.bash-git-prompt/gitprompt.sh
```

We can add the conda env by setting the changeps1 flag in conda (this can also be set in the condarc file)

```conda config --set changeps1 True```

This is more changes that I'm comfortable making since I'm not sure the best way to vendor code.

**Comment by dharhas** [comment]
two other things to change in the .bashrc

- remove the comment on `#force_color_prompt=yes`
- add `alias ls='ls --color=auto'`
